"""
Django settings for wis2watch project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import dj_database_url
import environ
from celery.schedules import crontab

from wis2watch.version import VERSION

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
)

dev_env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(BASE_DIR))), ".env")

if os.path.isfile(dev_env_path):
    # reading .env file
    environ.Env.read_env(dev_env_path)

DEBUG = env('DEBUG', False)

# Application definition

INSTALLED_APPS = [
    
    'daphne',
    'channels',
    
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.styleguide",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.humanize",
    
    "wagtailfontawesomesvg",
    "django_countries",
    "django_celery_beat",
    "django_celery_results",
    "django_vue_utilities",
    "rest_framework",
    
    "wis2watch.home",
    "wis2watch.core",
    "wis2watch.api",
    "wis2watch.ingest",
    "wis2watch.ws",
    "wis2watch.monitoring",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "wis2watch.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wis2watch.config.wsgi.application"
ASGI_APPLICATION = "wis2watch.config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_CONNECTION_MAX_AGE = env.int("DB_CONNECTION_MAX_AGE", default=0)
DB_CONN_HEALTH_CHECKS = env.bool("DB_CONN_HEALTH_CHECKS", default=False)
DB_DISABLE_SERVER_SIDE_CURSORS = env.bool("DB_DISABLE_SERVER_SIDE_CURSORS", default=False)
DB_SSL_REQUIRE = env.bool("DB_SSL_REQUIRE", default=False)

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=DB_CONNECTION_MAX_AGE,
        conn_health_checks=DB_CONN_HEALTH_CHECKS,
        disable_server_side_cursors=DB_DISABLE_SERVER_SIDE_CURSORS,
        ssl_require=DB_SSL_REQUIRE,
    )
}

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(BASE_DIR, "backup")}
DBBACKUP_CLEANUP_KEEP_MEDIA = 1
DBBACKUP_CLEANUP_KEEP = 1
DBBACKUP_CONNECTORS = {
    "default": {
        "CONNECTOR": "dbbackup.db.postgresql.PgDumpBinaryConnector",  # Use pg_dump binary
        "DUMP_SUFFIX": "-e plpgsql",  # dump only system extensions
        "RESTORE_SUFFIX": "--if-exists"  # Drop only if exists
    }
}

DBBACKUP_CONNECTOR_MAPPING = {
    "timescale.db.backends.postgis": "dbbackup.db.postgresql.PgDumpBinaryConnector",
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = env.str("LANGUAGE_CODE", default="en")

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Wagtail settings

WAGTAIL_SITE_NAME = env.str("WAGTAIL_SITE_NAME", "WIS2Watch")

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = env.str("WAGTAILADMIN_BASE_URL", "http://localhost:8000")

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

REDIS_HOST = env.str("REDIS_HOST", "redis")
REDIS_PORT = env.str("REDIS_PORT", "6379")
REDIS_USERNAME = env.str("REDIS_USER", "")
REDIS_PASSWORD = env.str("REDIS_PASSWORD", "")
REDIS_PROTOCOL = env.str("REDIS_PROTOCOL", "redis")
REDIS_URL = env.str(
    "REDIS_URL",
    f"{REDIS_PROTOCOL}://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0",
)

CELERY_BROKER_URL = REDIS_URL
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_SINGLETON_BACKEND_CLASS = (
    "wis2watch.celery_singleton_backend.RedisBackendForSingleton"
)

CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "wis2watch-default-cache",
        "VERSION": VERSION,
    },
}

CELERY_CACHE_BACKEND = "default"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1000,
            "expiry": 60,
        },
    },
}

# The countries WIS2Watch monitors, as ISO 3166 alpha-2 codes. Leave unset for
# the whole of Africa -- see wis2watch.core.countries for the default list.
WIS2WATCH_MONITORED_COUNTRIES = env.list("WIS2WATCH_MONITORED_COUNTRIES", default=[])

# The Global Broker the ingestion process subscribes to. Seeded as a message
# source on first run; thereafter the admin owns the record.
WIS2WATCH_GLOBAL_BROKER_URL = env.str(
    "WIS2WATCH_GLOBAL_BROKER_URL",
    "mqtts://everyone:everyone@globalbroker.meteo.fr:8883",
)

# How often the ingestion process re-reads the registry -- both the brokers it
# connects to and the centres it asks them for -- in seconds. This is what lets
# a catalogue sync widen coverage without restarting the process.
WIS2WATCH_SUBSCRIPTION_REFRESH_SECONDS = env.int(
    "WIS2WATCH_SUBSCRIPTION_REFRESH_SECONDS", 60
)

# How long the ingestion process may back off between attempts at a node's own
# broker, in seconds. Long, because a large share of these brokers are not
# reachable from outside at all: that is recorded as a finding about the centre,
# and knocking on dozens of dead brokers more often would tell us nothing new.
WIS2WATCH_ORIGIN_RECONNECT_MAX_SECONDS = env.int(
    "WIS2WATCH_ORIGIN_RECONNECT_MAX_SECONDS", 3600
)

# How long between periodic wildcard sweeps of the Global Broker, in seconds.
# The sweep is what finds centres of the monitored region publishing without a
# catalogue record: the per-centre subscriptions are built from the registry
# and so cannot name a centre nothing knows about.
WIS2WATCH_SWEEP_INTERVAL_SECONDS = env.int("WIS2WATCH_SWEEP_INTERVAL_SECONDS", 3600)

# How long one sweep carries its wildcard filter, in seconds. Bounded, because
# for as long as it is carried the connection is offered the whole world's
# traffic; what falls outside the monitored region is dropped as it is stored.
WIS2WATCH_SWEEP_DURATION_SECONDS = env.int("WIS2WATCH_SWEEP_DURATION_SECONDS", 60)

# How long raw notification messages are kept, in days. Deliberately short:
# raw messages answer "what went wrong recently", while the permanent record of
# the region lives in the hourly rollups, which are never expired.
WIS2WATCH_RAW_RETENTION_DAYS = env.int("WIS2WATCH_RAW_RETENTION_DAYS", 14)

# How far back each scheduled rollup run recomputes, in hours. Counts are
# derived from stored rows, so recomputing costs nothing but query time and a
# missed run corrects itself.
WIS2WATCH_ROLLUP_WINDOW_HOURS = env.int("WIS2WATCH_ROLLUP_WINDOW_HOURS", 48)

# How long a notification published at a node's own broker is given to appear
# on the Global Broker before its absence is recorded as a propagation gap, in
# minutes. Long enough to absorb ordinary propagation latency: reporting normal
# delay as loss would make the finding worthless.
WIS2WATCH_PROPAGATION_GRACE_MINUTES = env.int(
    "WIS2WATCH_PROPAGATION_GRACE_MINUTES", 15
)

# How far back each propagation evaluation re-examines, in hours. Clamped to
# the raw retention window in any case, beyond which the rows that would prove
# a notification did arrive are gone too.
WIS2WATCH_PROPAGATION_WINDOW_HOURS = env.int(
    "WIS2WATCH_PROPAGATION_WINDOW_HOURS", 48
)

# How many advertised files each centre is asked for per hour. This is the one
# job that makes requests of the monitored centres themselves rather than of a
# broker, so it is a sample and not a sweep: a tool that puts a centre's web
# server under load to check on it is a fault report of its own.
WIS2WATCH_LINK_PROBE_SAMPLE_SIZE = env.int("WIS2WATCH_LINK_PROBE_SAMPLE_SIZE", 5)

# How long a centre's server is given to answer a probe, in seconds. A slow
# answer is itself recorded, so this is long enough that only a server which has
# effectively stopped answering trips it.
WIS2WATCH_LINK_PROBE_TIMEOUT_SECONDS = env.int(
    "WIS2WATCH_LINK_PROBE_TIMEOUT_SECONDS", 15
)

# How long a centre may be quiet before the node overview calls it stale. A
# flat threshold, and only for sorting the table: whether a centre's quiet is
# actually a fault is judged per dataset against its own cadence, below.
WIS2WATCH_STALE_AFTER_HOURS = env.int("WIS2WATCH_STALE_AFTER_HOURS", 24)

# How much history each dataset's publishing rhythm is learned from, in days.
# Long, because that is what gives a daily or weekly dataset enough gaps to
# have a rhythm at all. A dataset publishing less often than a few times in the
# window is what the per-dataset manual override exists for.
WIS2WATCH_CADENCE_WINDOW_DAYS = env.int("WIS2WATCH_CADENCE_WINDOW_DAYS", 90)

# Which percentile of a dataset's own observed gaps becomes the interval it is
# expected to publish within. High enough that the gaps it routinely has are
# inside the expectation, low enough that a single past outage is not.
WIS2WATCH_CADENCE_PERCENTILE = env.int("WIS2WATCH_CADENCE_PERCENTILE", 95)

# How many observed gaps a dataset must show before an interval is learned from
# it at all. Below this it is left without one and reported as unjudged rather
# than given a guess.
WIS2WATCH_CADENCE_MIN_OBSERVATIONS = env.int("WIS2WATCH_CADENCE_MIN_OBSERVATIONS", 3)

# How many hourly buckets of traffic the node overview reports as recent
# volume, ending with the hour in progress.
WIS2WATCH_VOLUME_WINDOW_HOURS = env.int("WIS2WATCH_VOLUME_WINDOW_HOURS", 24)

# Over how many hours the gap reports work out each centre's share of messages
# carrying no station identifier. Wider than the overview's volume window,
# because a share is only worth reading over enough messages to have one: a
# centre publishing twice a day would otherwise be reported at nought or a
# hundred per cent depending on the day it was asked about.
WIS2WATCH_ATTRIBUTION_WINDOW_HOURS = env.int("WIS2WATCH_ATTRIBUTION_WINDOW_HOURS", 168)

# Who is told what changed, and who is told when the tool itself has stopped
# working. There is one operator of a regional diagnostic tool rather than a
# subscriber list, so both are configuration. Leaving the alert list unset
# sends alerts to whoever receives the digest, on the grounds that an
# installation which had configured one and not the other would think it was
# being watched.
WIS2WATCH_DIGEST_RECIPIENTS = env.list("WIS2WATCH_DIGEST_RECIPIENTS", default=[])
WIS2WATCH_ALERT_RECIPIENTS = env.list("WIS2WATCH_ALERT_RECIPIENTS", default=[])

# How long the Global Broker connection may be down, and how long nothing at
# all may be ingested, before either is mailed about, in minutes. Both are a
# first guess at what is more than a blip, and are meant to be revisited once
# the region's normal traffic patterns are known.
WIS2WATCH_BROKER_OUTAGE_MINUTES = env.int("WIS2WATCH_BROKER_OUTAGE_MINUTES", 5)
WIS2WATCH_INGESTION_STALL_MINUTES = env.int("WIS2WATCH_INGESTION_STALL_MINUTES", 15)

# How many of a report's findings one digest names before linking to the rest.
# Nothing is dropped -- what is left out is counted and the report is linked --
# but past a couple of dozen lines an email stops being read at all.
WIS2WATCH_DIGEST_SAMPLE_SIZE = env.int("WIS2WATCH_DIGEST_SAMPLE_SIZE", 20)

# How long a finding may be absent from its report before the digest calls it
# cleared, in hours. A report can stop listing a finding without the problem
# having gone anywhere -- propagation gaps are withheld for a centre whose own
# broker is unreachable, and a quiet centre falls out of the attribution
# window -- and announcing those as fixed, then again as new when they return,
# is exactly what a digest must not do.
WIS2WATCH_FINDING_GRACE_HOURS = env.int("WIS2WATCH_FINDING_GRACE_HOURS", 48)

# Where the digest and the alerts are sent from. Without a mail host nothing
# is sent at all, which is why the recipients above are the setting an
# installation is most likely to have forgotten: the tool goes on finding
# everything it would have said.
EMAIL_HOST = env.str("EMAIL_HOST", "")
# Read as text first because the deployment passes every unset variable as an
# empty string, which is not a number and would stop the process from starting
# over a setting nothing was going to use.
EMAIL_PORT = int(env.str("EMAIL_PORT", "") or 25)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", False)
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", "wis2watch@localhost")

WIS2WATCH_LOG_LEVEL = env.str("WIS2WATCH_LOG_LEVEL", "INFO")
WIS2WATCH_DATABASE_LOG_LEVEL = env.str("WIS2WATCH_DATABASE_LOG_LEVEL", "ERROR")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "%(levelname)s %(asctime)s %(name)s.%(funcName)s:%(lineno)s- %("
                      "message)s "
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": WIS2WATCH_LOG_LEVEL,
            "propagate": True,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": WIS2WATCH_DATABASE_LOG_LEVEL,
    },
}

VUE_FRONTEND_USE_TYPESCRIPT = False
VUE_FRONTEND_USE_DEV_SERVER = DEBUG
VUE_FRONTEND_DEV_SERVER_URL = 'http://localhost:5173'
VUE_FRONTEND_DEV_SERVER_PATH = '/static/vue/src'
VUE_FRONTEND_STATIC_PATH = 'vue'

# Scheduled work is sync, rollup, cleanup and mail only. Broker connections are
# stateful and long-lived, and belong to the ingestion supervisor rather than to
# a task queue -- see wis2watch.ingest.supervisor.
CELERY_BEAT_SCHEDULE = {
    'sync-catalogues': {
        'task': 'wis2watch.core.tasks.run_sync_catalogues',
        'schedule': 21600.0,  # Every 6 hours
    },
    'sync-node-stations': {
        'task': 'wis2watch.core.tasks.run_sync_all_node_stations',
        'schedule': 3600.0,  # Every hour
    },
    # OSCAR changes slowly: a country's declared set moves in months, and the
    # whole monitored region is read territory by territory in one run.
    'sync-oscar-stations': {
        'task': 'wis2watch.core.tasks.run_sync_oscar_stations',
        'schedule': 604800.0,  # Weekly
    },
    'update-rollups': {
        'task': 'wis2watch.core.tasks.run_update_rollups',
        'schedule': 900.0,  # Every 15 minutes
    },
    # A publishing rhythm is learned from months of buckets and moves in weeks,
    # so a daily run arrives at the same number a frequent one would.
    'learn-cadence-baselines': {
        'task': 'wis2watch.core.tasks.run_learn_cadence_baselines',
        'schedule': 86400.0,  # Daily
    },
    'evaluate-propagation': {
        'task': 'wis2watch.core.tasks.run_evaluate_propagation',
        'schedule': 900.0,  # Every 15 minutes
    },
    # Hourly, a few minutes past, because a run samples the last hour that is
    # over and there is nothing to gain by asking the moment it closes.
    'probe-canonical-links': {
        'task': 'wis2watch.core.tasks.run_probe_canonical_links',
        'schedule': crontab(minute=5),
    },
    'expire-raw-messages': {
        'task': 'wis2watch.core.tasks.run_expire_raw_messages',
        'schedule': 86400.0,  # Daily
    },
    # Early, in the installation's own time zone, so that what changed
    # overnight is read before the day starts rather than during it.
    'send-daily-digest': {
        'task': 'wis2watch.core.tasks.run_send_daily_digest',
        'schedule': crontab(hour=6, minute=0),
    },
    # Far oftener than the outages it judges: a check on a five-minute beat
    # could not tell a five-minute outage from a twenty-minute one.
    'check-hard-failures': {
        'task': 'wis2watch.core.tasks.run_check_hard_failures',
        'schedule': 60.0,  # Every minute
    },
}
