"""Findings: what the stored observations add up to.

Everything in here reads the database and returns findings -- structures a
view or an email can render without knowing how they were arrived at. Nothing
in here writes, fetches or connects.

This is the second of the project's two test seams. Its functions are tested
against a seeded database rather than hand-built inputs, because the mistakes
that matter here -- a bucket an hour out, a join that multiplies rows, a
centre missing from a table because it has nothing to join to -- produce a
confident wrong answer rather than an exception, and only real rows expose
them.
"""

from .gaps import (
    GAP_REPORTS,
    UNATTRIBUTED_MESSAGES_SLUG,
    DeclarationDrift,
    DeclaringCentre,
    DriftingDatasetRow,
    FailingCatalogueRow,
    GapReport,
    GapReportSummary,
    Notice,
    PropagationGapRow,
    RegistryStanding,
    SilentStationRow,
    SteppedOverRunRow,
    UnansweredRegistryRow,
    UnattributedRateRow,
    UndeclaredStationRow,
    UnregisteredCentreRow,
    attribution_window_label,
    catalogues_that_keep_failing,
    datasets_out_of_step,
    datasets_out_of_step_unasked_centres,
    default_attribution_window_hours,
    default_catalogue_failing_days,
    default_catalogue_failing_share,
    default_registry_unanswered_hours,
    default_stepped_over_days,
    gap_report,
    gap_report_summaries,
    propagation_gaps,
    propagation_gaps_left_out,
    propagation_gaps_unsettled,
    registries_not_answering,
    registries_not_answering_caveat,
    registries_not_answering_centre_ids,
    stations_declared_but_silent,
    stations_declared_but_silent_unasked_centres,
    stations_transmitting_undeclared,
    syncs_stepping_over_records,
    unattributed_rates,
    unregistered_centres,
)
from .node_detail import (
    NodeDatasetRow,
    NodeDetail,
    OriginState,
    SyncRunRow,
    SyncScope,
    node_detail,
)
from .overview import (
    CachePickup,
    NodeOverviewRow,
    NodeStanding,
    TransmissionStanding,
    default_volume_hours,
    node_overview,
)
from .reachability import OriginReachability, OriginTransport, OriginWatch
from .silence import (
    DatasetSilenceRow,
    Expectation,
    NodeSilence,
    Silence,
    dataset_silence,
    silence_by_node,
)
from .staleness import Staleness
from .statistics import (
    AllNodesStatistics,
    Bucket,
    DailyActivity,
    DatasetActivity,
    HourlyActivity,
    NodeStationDetail,
    NodeStationStatistics,
    NodeStatisticsRow,
    NodeStatisticsSummary,
    NowBlock,
    StationDayActivity,
    StationHourActivity,
    StationIdentity,
    StationNowBlock,
    StationRow,
    StationWindowStats,
    UnknownStation,
    Vantage,
    WindowBounds,
    WindowOption,
    WindowStats,
    all_nodes_statistics,
    node_station_detail,
    node_station_statistics,
    node_statistics_summary,
)
from .stations import NodeStationRow, StationStanding, node_stations
from .windows import Grain, UnknownWindow, Window

__all__ = [
    "GAP_REPORTS",
    "UNATTRIBUTED_MESSAGES_SLUG",
    "AllNodesStatistics",
    "Bucket",
    "CachePickup",
    "DailyActivity",
    "DatasetActivity",
    "DatasetSilenceRow",
    "DeclarationDrift",
    "DriftingDatasetRow",
    "Expectation",
    "FailingCatalogueRow",
    "GapReport",
    "GapReportSummary",
    "Grain",
    "HourlyActivity",
    "NodeDatasetRow",
    "NodeDetail",
    "NodeOverviewRow",
    "NodeSilence",
    "NodeStanding",
    "NodeStationDetail",
    "NodeStationRow",
    "NodeStationStatistics",
    "NodeStatisticsRow",
    "NodeStatisticsSummary",
    "Notice",
    "NowBlock",
    "OriginReachability",
    "OriginState",
    "OriginTransport",
    "OriginWatch",
    "PropagationGapRow",
    "RegistryStanding",
    "Silence",
    "SilentStationRow",
    "Staleness",
    "StationDayActivity",
    "StationHourActivity",
    "StationIdentity",
    "StationNowBlock",
    "StationRow",
    "StationStanding",
    "StationWindowStats",
    "SteppedOverRunRow",
    "SyncRunRow",
    "SyncScope",
    "TransmissionStanding",
    "UnansweredRegistryRow",
    "UnattributedRateRow",
    "UndeclaredStationRow",
    "UnknownStation",
    "UnknownWindow",
    "UnregisteredCentreRow",
    "Vantage",
    "Window",
    "WindowBounds",
    "WindowOption",
    "WindowStats",
    "all_nodes_statistics",
    "attribution_window_label",
    "catalogues_that_keep_failing",
    "dataset_silence",
    "datasets_out_of_step",
    "datasets_out_of_step_unasked_centres",
    "default_attribution_window_hours",
    "default_catalogue_failing_days",
    "default_catalogue_failing_share",
    "default_registry_unanswered_hours",
    "default_stepped_over_days",
    "default_volume_hours",
    "gap_report",
    "gap_report_summaries",
    "node_detail",
    "node_overview",
    "node_station_detail",
    "node_station_statistics",
    "node_stations",
    "node_statistics_summary",
    "propagation_gaps",
    "propagation_gaps_left_out",
    "propagation_gaps_unsettled",
    "registries_not_answering",
    "registries_not_answering_caveat",
    "registries_not_answering_centre_ids",
    "silence_by_node",
    "DeclaringCentre",
    "stations_declared_but_silent",
    "stations_declared_but_silent_unasked_centres",
    "stations_transmitting_undeclared",
    "syncs_stepping_over_records",
    "unattributed_rates",
    "unregistered_centres",
]
