# Generated by Django 5.2.7 on 2026-08-11 10:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_extensions.db.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDiscoveryCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('centre_id', models.CharField(help_text='WIS2 centre ID of the catalogue', max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(max_length=500)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('is_writer', models.BooleanField(default=False, help_text='Only the writing catalogue may create or update registry records')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global Discovery Catalogue',
                'verbose_name_plural': 'Global Discovery Catalogues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('wigos_id', models.CharField(help_text='WIGOS station identifier', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, help_text='Location of the station, where it is known', null=True, srid=4326)),
                ('facility_type', models.CharField(blank=True, choices=[('landFixed', 'Land Fixed'), ('landMobile', 'Land Mobile'), ('sea', 'Sea'), ('airFixed', 'Air Fixed'), ('airMobile', 'Air Mobile')], max_length=20)),
                ('territory', models.CharField(blank=True, max_length=100)),
                ('wmo_region', models.CharField(blank=True, max_length=100)),
                ('operating_status', models.CharField(blank=True, help_text='Operational status as reported by OSCAR/Surface', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WIS2Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('centre_id', models.CharField(help_text='WIS2 centre ID, e.g. ke-kmd', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Friendly name for this node', max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Derived from the centre ID prefix when left blank', max_length=2, verbose_name='Country')),
                ('node_type', models.CharField(choices=[('wis2box', 'WIS2Box'), ('other', 'Other Software')], default='wis2box', max_length=20)),
                ('base_url', models.URLField(blank=True, help_text='Base URL of the node', max_length=500)),
                ('discovery_metadata_url', models.URLField(blank=True, help_text='Custom URL for discovery metadata. Auto-generated for wis2box.', max_length=500)),
                ('stations_url', models.URLField(blank=True, help_text='Custom URL for stations list. Auto-generated for wis2box.', max_length=500)),
                ('verify_ssl', models.BooleanField(default=True, help_text='Verify SSL certificates when connecting to the node')),
                ('is_manually_managed', models.BooleanField(default=False, help_text='Catalogue syncs never overwrite fields on a manually managed node')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'WIS2 Node',
                'verbose_name_plural': 'WIS2 Nodes',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('global_broker', 'Global Broker'), ('origin_broker', 'Origin Broker')], default='global_broker', max_length=20)),
                ('centre_id', models.CharField(blank=True, help_text='WIS2 centre ID of the broker, where it has one', max_length=200)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reachable', models.BooleanField(default=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('node', models.ForeignKey(blank=True, help_text='The node this broker belongs to, for origin brokers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sources', to='wis2watchcore.wis2node')),
            ],
            options={
                'verbose_name': 'Message Source',
                'verbose_name_plural': 'Message Sources',
                'ordering': ['source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('identifier', models.CharField(help_text='URN identifier of the dataset', max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('wmo_data_policy', models.CharField(choices=[('core', 'Core'), ('recommended', 'Recommended')], max_length=20)),
                ('wmo_topic_hierarchy', models.CharField(help_text='MQTT topic hierarchy for this dataset', max_length=500, unique=True)),
                ('self_link', models.URLField(blank=True, max_length=1000)),
                ('collection_link', models.URLField(blank=True, max_length=1000)),
                ('raw_json', models.JSONField(help_text='Complete raw JSON from discovery metadata')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('metadata_created', models.DateTimeField(blank=True, null=True)),
                ('metadata_updated', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='wis2watchcore.wis2node')),
            ],
            options={
                'ordering': ['node', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('catalogue', 'Global Discovery Catalogue'), ('discovery_metadata', 'Discovery Metadata'), ('node_stations', 'Node Stations'), ('oscar_stations', 'OSCAR Stations')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('items_found', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='wis2watchcore.globaldiscoverycatalogue')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='wis2watchcore.wis2node')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['node', '-started_at'], name='wis2watchco_node_id_fc1859_idx'), models.Index(fields=['sync_type', '-started_at'], name='wis2watchco_sync_ty_b08ea4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_type', models.CharField(choices=[('oscar', 'Declared in OSCAR/Surface'), ('node_registry', "Declared by the node's station registry"), ('observed', 'Observed in notification messages')], max_length=20)),
                ('local_name', models.CharField(blank=True, help_text='Name the node assigns to this station', max_length=200)),
                ('local_id', models.CharField(blank=True, help_text='Identifier the node assigns to this station', max_length=100)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wis2watchcore.station')),
                ('node', models.ForeignKey(blank=True, help_text='The node that declared or transmitted the station, where applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_declarations', to='wis2watchcore.wis2node')),
            ],
            options={
                'verbose_name': 'Station Source',
                'verbose_name_plural': 'Station Sources',
                'ordering': ['station', 'source_type'],
                'constraints': [models.UniqueConstraint(fields=('station', 'source_type', 'node'), name='unique_station_declaration_per_node'), models.UniqueConstraint(condition=models.Q(('node__isnull', True)), fields=('station', 'source_type'), name='unique_station_declaration_without_node')],
            },
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('notification_id', models.CharField(help_text="The notification's own UUID", max_length=255)),
                ('topic', models.CharField(help_text='Raw MQTT topic the message arrived on', max_length=1000)),
                ('wigos_station_id', models.CharField(blank=True, help_text='WIGOS station identifier declared by the message, when present', max_length=100)),
                ('data_id', models.CharField(blank=True, max_length=500)),
                ('metadata_id', models.CharField(blank=True, help_text='Discovery metadata identifier declared by the message', max_length=500)),
                ('received_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('canonical_link', models.URLField(blank=True, max_length=1000)),
                ('raw_json', models.JSONField()),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='wis2watchcore.dataset')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wis2watchcore.messagesource')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='wis2watchcore.station')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='wis2watchcore.wis2node')),
            ],
            options={
                'verbose_name': 'Notification Message',
                'verbose_name_plural': 'Notification Messages',
                'indexes': [models.Index(fields=['notification_id'], name='wis2watchco_notific_76968d_idx'), models.Index(fields=['topic'], name='wis2watchco_topic_ebb5f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'notification_id', 'time'), name='unique_notification_per_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagesource',
            constraint=models.UniqueConstraint(condition=models.Q(('node__isnull', False)), fields=('node', 'source_type'), name='unique_source_type_per_node'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['wmo_topic_hierarchy'], name='wis2watchco_wmo_top_795672_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['status'], name='wis2watchco_status_e90a2f_idx'),
        ),
    ]
