# Generated by Django 5.2.7 on 2025-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wis2node',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Verify SSL certificates when connecting to the node'),
        ),
    ]
