# Generated by Django 5.2.7 on 2026-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='items_errored',
            field=models.IntegerField(default=0, help_text='Items the run could not store, having stepped over them'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Why the run failed as a whole, as opposed to a single item'),
        ),
    ]
