# Generated by Django 5.2.7 on 2026-08-11 18:58

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0002_synclog_items_errored_alter_synclog_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('last_message_at', models.DateTimeField(db_index=True, help_text='Publication time of the most recent message seen from this node')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to='wis2watchcore.wis2node')),
            ],
            options={
                'verbose_name': 'Node Last Seen',
                'verbose_name_plural': 'Node Last Seen',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hour', models.DateTimeField(db_index=True, help_text='Start of the UTC hour this count covers')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(blank=True, help_text='Null for traffic on a topic no dataset claims', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollups', to='wis2watchcore.dataset')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='wis2watchcore.wis2node')),
                ('source', models.ForeignKey(help_text='The vantage point these messages were observed from', on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='wis2watchcore.messagesource')),
                ('station', models.ForeignKey(blank=True, help_text='Null for messages carrying no known station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollups', to='wis2watchcore.station')),
            ],
            options={
                'verbose_name': 'Hourly Rollup',
                'verbose_name_plural': 'Hourly Rollups',
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['node', '-hour'], name='wis2watchco_node_id_801c17_idx')],
                'constraints': [models.UniqueConstraint(fields=('hour', 'source', 'node', 'dataset', 'station'), name='unique_rollup_per_hour_and_grain', nulls_distinct=False)],
            },
        ),
    ]
