# Generated by Django 5.2.7 on 2026-08-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0004_alter_messagesource_is_reachable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropagationGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(help_text="The notification's own UUID, as both vantage points carry it", max_length=255)),
                ('topic', models.CharField(help_text='Raw MQTT topic the notification was published on', max_length=1000)),
                ('published_at', models.DateTimeField(help_text="The notification's own publication time")),
                ('observed_at_origin', models.DateTimeField(help_text="When this tool saw the notification at the node's own broker")),
                ('detected_at', models.DateTimeField(help_text='When the evaluation concluded the world had not seen it')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the notification was finally seen on the Global Broker', null=True)),
                ('dataset', models.ForeignKey(blank=True, help_text='Null where the topic belongs to no dataset the registry knows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagation_gaps', to='wis2watchcore.dataset')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagation_gaps', to='wis2watchcore.wis2node')),
                ('origin_source', models.ForeignKey(blank=True, help_text='The vantage point that saw the notification published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagation_gaps', to='wis2watchcore.messagesource')),
            ],
            options={
                'verbose_name': 'Propagation Gap',
                'verbose_name_plural': 'Propagation Gaps',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['node', '-published_at'], name='wis2watchco_node_id_c8971d_idx'), models.Index(fields=['resolved_at'], name='wis2watchco_resolve_4fafb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('node', 'notification_id'), name='unique_propagation_gap_per_notification')],
            },
        ),
    ]
