# Generated by Django 5.2.7 on 2026-08-12 08:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0005_propagationgap'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='other_wigos_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Further WIGOS station identifiers the same station is known by', size=None),
        ),
    ]
