# Generated by Django 5.2.7 on 2026-08-12 10:33

import django_countries.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0008_hourlyrollup_wis2watchco_dataset_bd24eb_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('catalogue', 'Global Discovery Catalogue'), ('discovery_metadata', 'Discovery Metadata'), ('node_stations', 'Node Stations'), ('oscar_stations', 'OSCAR Stations'), ('wildcard_sweep', 'Wildcard Sweep')], max_length=50),
        ),
        migrations.CreateModel(
            name='UnregisteredCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('centre_id', models.CharField(help_text='WIS2 centre ID observed publishing, e.g. ke-kmd', max_length=200, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Derived from the centre ID prefix', max_length=2, verbose_name='Country')),
                ('sample_topic', models.CharField(blank=True, help_text='A topic this centre was last seen publishing on', max_length=1000)),
                ('first_seen_at', models.DateTimeField(help_text='When a sweep first saw this centre publishing')),
                ('last_seen_at', models.DateTimeField(help_text='When a sweep last saw this centre publishing')),
                ('registered_at', models.DateTimeField(blank=True, help_text='When the registry caught up with this centre', null=True)),
            ],
            options={
                'verbose_name': 'Unregistered Centre',
                'verbose_name_plural': 'Unregistered Centres',
                'ordering': ['centre_id'],
                'indexes': [models.Index(fields=['registered_at'], name='wis2watchco_registe_94fa75_idx')],
            },
        ),
    ]
