# Generated by Django 5.2.7 on 2026-08-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0009_alter_synclog_sync_type_unregisteredcentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesource',
            name='carried_by',
            field=models.ForeignKey(blank=True, help_text="The broker connection this vantage point's traffic arrives on, for vantage points that are not dialled separately", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carried_sources', to='wis2watchcore.messagesource'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='source_type',
            field=models.CharField(choices=[('global_broker', 'Global Broker'), ('global_cache', 'Global Cache'), ('origin_broker', 'Origin Broker')], default='global_broker', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='messagesource',
            constraint=models.UniqueConstraint(condition=models.Q(('carried_by__isnull', False)), fields=('carried_by', 'source_type'), name='unique_source_type_per_carrier'),
        ),
    ]
