# Generated by Django 5.2.7 on 2026-08-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0010_messagesource_carried_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(help_text='The notification that advertised this link', max_length=255)),
                ('url', models.URLField(help_text='The canonical link, as the notification gave it', max_length=1000)),
                ('outcome', models.CharField(choices=[('retrievable', 'Retrievable'), ('missing', 'Missing'), ('forbidden', 'Access denied'), ('server_error', 'Server error'), ('unexpected_status', 'Unexpected status'), ('not_probeable', 'Server refuses headers-only requests'), ('tls_error', 'Certificate or TLS failure'), ('unreachable', 'Connection failed'), ('timeout', 'Timed out'), ('bad_url', 'Link is not a fetchable URL')], max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='Null where no HTTP response came back at all', null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='How long the request took, including a failure', null=True)),
                ('error', models.TextField(blank=True, help_text='What the transport failure said, in its own words')),
                ('hour', models.DateTimeField(help_text='Start of the UTC hour the sampled notifications fall in')),
                ('probed_at', models.DateTimeField(help_text='When the request was made')),
                ('dataset', models.ForeignKey(blank=True, help_text='Null where the topic belongs to no dataset the registry knows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_probes', to='wis2watchcore.dataset')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_probes', to='wis2watchcore.wis2node')),
            ],
            options={
                'verbose_name': 'Link Probe',
                'verbose_name_plural': 'Link Probes',
                'ordering': ['-probed_at'],
                'indexes': [models.Index(fields=['node', '-probed_at'], name='wis2watchco_node_id_8d4bed_idx'), models.Index(fields=['node', 'hour'], name='wis2watchco_node_id_7f65d0_idx'), models.Index(fields=['outcome'], name='wis2watchco_outcome_4ab1bd_idx')],
            },
        ),
    ]
