# Generated by Django 5.2.7 on 2026-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0011_linkprobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('catalogue', 'Global Discovery Catalogue'), ('discovery_metadata', 'Discovery Metadata'), ('link_probes', 'Canonical Link Probes'), ('node_stations', 'Node Stations'), ('oscar_stations', 'OSCAR Stations'), ('wildcard_sweep', 'Wildcard Sweep')], max_length=50),
        ),
    ]
