# Generated by Django 5.2.7 on 2026-08-12 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0012_alter_synclog_sync_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='received_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this tool stored the message, as against when it was published'),
        ),
        migrations.CreateModel(
            name='HardFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('global_broker_lost', 'Global Broker connection lost'), ('ingestion_stalled', 'Ingestion stalled')], max_length=50)),
                ('detail', models.TextField(blank=True, help_text='What was found to be wrong, as it stood when last checked')),
                ('started_at', models.DateTimeField(help_text='When the failure began, as closely as it can be told')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the failure was announced, if it lasted long enough to be', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the failure was seen to have cleared', null=True)),
            ],
            options={
                'verbose_name': 'Hard Failure',
                'verbose_name_plural': 'Hard Failures',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['kind', '-started_at'], name='wis2watchco_kind_67cd9c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('kind',), name='unique_open_hard_failure_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='ReportedFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_slug', models.CharField(help_text='Which gap report this finding came from', max_length=100)),
                ('key', models.CharField(help_text='What identifies the finding within its report', max_length=500)),
                ('summary', models.CharField(help_text='How the finding read when it was last reported', max_length=1000)),
                ('reported_at', models.DateTimeField(help_text='When a digest carried this finding')),
            ],
            options={
                'verbose_name': 'Reported Finding',
                'verbose_name_plural': 'Reported Findings',
                'ordering': ['report_slug', 'key'],
                'constraints': [models.UniqueConstraint(fields=('report_slug', 'key'), name='unique_reported_finding')],
            },
        ),
    ]
