# Generated by Django 5.2.7 on 2026-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0013_alter_notificationmessage_received_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldiscoverycatalogue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Switch a catalogue off here rather than deleting it: the Global Services this release ships with are recreated on the next start, and a deleted one comes back'),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Switch a broker off here rather than deleting it: the Global Brokers this release ships with are recreated on the next start, and an origin broker by the next catalogue sync'),
        ),
        migrations.AddConstraint(
            model_name='messagesource',
            constraint=models.UniqueConstraint(condition=models.Q(('centre_id', ''), _negated=True), fields=('centre_id', 'source_type'), name='unique_source_type_per_centre'),
        ),
    ]
