# Generated by Django 5.2.7 on 2026-08-20 17:36

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0019_summarise_the_history_already_held'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily_digest', 'Daily digest'), ('hard_failure', 'Hard failure alert')], help_text='Which of the things this tool sends this message was', max_length=50)),
                ('subject', models.CharField(help_text='The subject as it was sent, prefix and all', max_length=500)),
                ('summary', models.CharField(blank=True, help_text='What the message was about, in one line, from whatever composed it', max_length=1000)),
                ('body', models.TextField(blank=True, help_text='The message itself, as it was rendered')),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Who it was addressed to, as configured at the time', size=None)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('no_recipients', 'Nobody to send it to'), ('failed', 'Failed')], help_text='How the attempt ended', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Why it did not get there, where it did not')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was composed and handed to the mail backend')),
            ],
            options={
                'verbose_name': 'Outgoing Email',
                'verbose_name_plural': 'Outgoing Email',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['kind', '-attempted_at'], name='wis2watchco_kind_d2f598_idx')],
            },
        ),
    ]
