# Generated by Django 5.2.7 on 2026-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0020_what_the_tool_has_told_anybody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardfailure',
            name='kind',
            field=models.CharField(choices=[('global_broker_lost', 'Global Broker connection lost'), ('global_broker_unreliable', 'Global Broker unreliable'), ('ingestion_stalled', 'Ingestion stalled')], max_length=50),
        ),
    ]
