# Generated by Django 5.2.7 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0021_a_broker_that_keeps_dropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardfailure',
            name='kind',
            field=models.CharField(choices=[('global_broker_lost', 'Global Broker connection lost'), ('global_broker_unreliable', 'Global Broker unreliable'), ('ingestion_stalled', 'Ingestion stalled'), ('catalogue_writer_stale', 'Registry catalogue not syncing')], max_length=50),
        ),
    ]
