# Generated by Django 5.2.7 on 2026-08-25 15:53

"""Somewhere to record which address a node's records last pointed at.

Without it, a base URL that is dead and a base URL somebody corrected by hand
look identical, and a sync that re-asserted the catalogue's address over the
second would erase an operator's work on a six-hourly schedule.

The backfill is the awkward part, and it is a reading of the existing
contract rather than a fact in the data. Nothing recorded who wrote a node's
base URL, so for rows that already exist this assumes the catalogue did --
which is true of every node the fill created, and false only for one an
operator corrected without flagging it manually managed. That flag is how this
registry has always been told to leave a node alone: the sync skips such a node
entirely, overwriting its country and its broker otherwise, so a hand-corrected
node that is not flagged is already being written over today. Manually managed
nodes are therefore left with a blank, which reads as "not the catalogue's" and
keeps them out of any re-assertion for good.

Leaving every row blank instead was the alternative, and it does not work: a
node whose host moved before this shipped would have a base URL that matches
nothing the catalogue now says, and would be read as somebody's correction for
ever -- which is exactly the node all of this exists to repair.
"""

from django.db import migrations, models
from django.db.models import F


def the_catalogue_wrote_what_is_there(apps, schema_editor):
    """Treat an unflagged node's existing address as the catalogue's own."""
    apps.get_model("wis2watchcore", "WIS2Node").objects.filter(
        is_manually_managed=False
    ).exclude(base_url="").update(advertised_base_url=F("base_url"))


def forget_it_again(apps, schema_editor):
    """Nothing to restore: the column goes with the field."""


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0022_a_registry_that_stopped_being_rebuilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='wis2node',
            name='advertised_base_url',
            field=models.URLField(blank=True, editable=False, help_text="The address this centre's own catalogue records last pointed at. Kept beside the address in use so the two can be told apart: they agree while the catalogue's address is the one being asked, and differ once somebody has corrected it by hand.", max_length=500),
        ),
        migrations.RunPython(the_catalogue_wrote_what_is_there, forget_it_again),
    ]
