# Generated by Django 5.2.7 on 2026-08-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0023_a_registry_this_tool_may_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationActivityBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hours', models.FloatField(help_text='How many hours of a day this station is normally heard in')),
                ('observations', models.PositiveIntegerField(help_text='How many observed days the figure was learned from')),
                ('learned_at', models.DateTimeField(help_text='When the run that produced this figure read the history')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_activity_baselines', to='wis2watchcore.wis2node')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_baselines', to='wis2watchcore.station')),
            ],
            options={
                'verbose_name': 'Station Activity Baseline',
                'verbose_name_plural': 'Station Activity Baselines',
                'ordering': ['node', 'station'],
                'constraints': [models.UniqueConstraint(fields=('node', 'station'), name='unique_station_activity_baseline_per_node')],
            },
        ),
    ]
