# Generated by Django 5.2.7 on 2026-08-27 18:17

"""Keep, on the run itself, which records it stepped over and what refused them.

A run that read sixty-three records, applied fifty-four and stepped over nine
recorded the nine as a number. Which nine, and what refused them, existed only
as a warning in a worker's output -- so a unique constraint dropped a centre's
largest observation feed for four days with every surface of this tool
reporting the run as a partial success and nothing more.

Empty for every run already recorded, which is honest: those runs kept no
reasons, and inventing one now would be worse than a row that says nothing.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0026_several_datasets_may_share_a_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='stepped_over',
            field=models.JSONField(blank=True, default=list, help_text='Which items the run could not store, and what refused each one: one object per item, with an ``item`` and a ``reason``'),
        ),
    ]
