"""Give a run somewhere to say what it retired and what its history did.

A retirement moves a centre's largest observation feed from one dataset to
another, and a run that only logged it would leave the region's history
rewritten with nothing to check it against afterwards. So the counts are
columns and the detail is a row's worth of JSON: which datasets were retired,
where each history went, and -- where it could not go anywhere -- which
datasets the centre left the choice between.

Every column is additive with a default, so runs recorded before this say
nothing about retirement rather than claiming they retired nothing.
"""

# Generated by Django 5.2.7 on 2026-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2watchcore', '0029_every_dataset_says_which_catalogue_declared_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='items_retired',
            field=models.IntegerField(default=0, help_text='Records the source has stopped declaring, retired by this run'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='retired',
            field=models.JSONField(blank=True, default=list, help_text='Which records the run retired, and where their history went'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='rollups_repointed',
            field=models.IntegerField(default=0, help_text='Hourly counts moved onto the record that really earned them'),
        ),
    ]
